export interface Artwork {
  id: string;
  path: string;
  associatedProject: string;
  fundingAmount: number;
  funder: string;
}

const DUMMY_ARTWORK = [
  {
    id: 'uuid-1',
    path: 'aperture.jpg',
    associatedProject: 'Novel Methods of Tuning Neuroplasticity',
    fundingAmount: 45,
    funder: 'cornperson.eth',
  },
  {
    id: 'uuid-2',
    path: 'cell.jpg',
    associatedProject: 'Novel Methods of Tuning Neuroplasticity',
    fundingAmount: 45,
    funder: 'cornperson.eth',
  },
  {
    id: 'uuid-3',
    path: 'cyber.jpg',
    associatedProject: 'Novel Methods of Tuning Neuroplasticity',
    fundingAmount: 45,
    funder: 'cornperson.eth',
  },
  {
    id: 'uuid-4',
    path: 'flower.jpg',
    associatedProject: 'Novel Methods of Tuning Neuroplasticity',
    fundingAmount: 45,
    funder: 'cornperson.eth',
  },
  {
    id: 'uuid-5',
    path: 'glow.jpg',
    associatedProject: 'Novel Methods of Tuning Neuroplasticity',
    fundingAmount: 45,
    funder: 'cornperson.eth',
  },
  {
    id: 'uuid-6',
    path: 'helix.jpg',
    associatedProject: 'Novel Methods of Tuning Neuroplasticity',
    fundingAmount: 45,
    funder: 'cornperson.eth',
  },
  {
    id: 'uuid-7',
    path: 'ignition.jpg',
    associatedProject: 'Novel Methods of Tuning Neuroplasticity',
    fundingAmount: 45,
    funder: 'cornperson.eth',
  },
  {
    id: 'uuid-8',
    path: 'iso.jpg',
    associatedProject: 'Novel Methods of Tuning Neuroplasticity',
    fundingAmount: 45,
    funder: 'cornperson.eth',
  },
  {
    id: 'uuid-9',
    path: 'lasers.jpg',
    associatedProject: 'Novel Methods of Tuning Neuroplasticity',
    fundingAmount: 45,
    funder: 'cornperson.eth',
  },
  {
    id: 'uuid-10',
    path: 'molecule.jpg',
    associatedProject: 'Novel Methods of Tuning Neuroplasticity',
    fundingAmount: 45,
    funder: 'cornperson.eth',
  },
  {
    id: 'uuid-11',
    path: 'network.jpg',
    associatedProject: 'Novel Methods of Tuning Neuroplasticity',
    fundingAmount: 45,
    funder: 'cornperson.eth',
  },
  {
    id: 'uuid-12',
    path: 'node.jpg',
    associatedProject: 'Novel Methods of Tuning Neuroplasticity',
    fundingAmount: 45,
    funder: 'cornperson.eth',
  },
  {
    id: 'uuid-13',
    path: 'nucleus.jpg',
    associatedProject: 'Novel Methods of Tuning Neuroplasticity',
    fundingAmount: 45,
    funder: 'cornperson.eth',
  },
  {
    id: 'uuid-14',
    path: 'planets.jpg',
    associatedProject: 'Novel Methods of Tuning Neuroplasticity',
    fundingAmount: 45,
    funder: 'cornperson.eth',
  },
  {
    id: 'uuid-15',
    path: 'portal.jpg',
    associatedProject: 'Novel Methods of Tuning Neuroplasticity',
    fundingAmount: 45,
    funder: 'cornperson.eth',
  },
  {
    id: 'uuid-16',
    path: 'surface.jpg',
    associatedProject: 'Novel Methods of Tuning Neuroplasticity',
    fundingAmount: 45,
    funder: 'cornperson.eth',
  },
  {
    id: 'uuid-17',
    path: 'threads.jpg',
    associatedProject: 'Novel Methods of Tuning Neuroplasticity',
    fundingAmount: 45,
    funder: 'cornperson.eth',
  },
  {
    id: 'uuid-18',
    path: 'tron.jpg',
    associatedProject: 'Novel Methods of Tuning Neuroplasticity',
    fundingAmount: 45,
    funder: 'cornperson.eth',
  },
  {
    id: 'uuid-19',
    path: 'aperture.jpg',
    associatedProject: 'Novel Methods of Tuning Neuroplasticity',
    fundingAmount: 45,
    funder: 'cornperson.eth',
  },
  {
    id: 'uuid-20',
    path: 'cell.jpg',
    associatedProject: 'Novel Methods of Tuning Neuroplasticity',
    fundingAmount: 45,
    funder: 'cornperson.eth',
  },
  {
    id: 'uuid-21',
    path: 'cyber.jpg',
    associatedProject: 'Novel Methods of Tuning Neuroplasticity',
    fundingAmount: 45,
    funder: 'cornperson.eth',
  },
  {
    id: 'uuid-22',
    path: 'flower.jpg',
    associatedProject: 'Novel Methods of Tuning Neuroplasticity',
    fundingAmount: 45,
    funder: 'cornperson.eth',
  },
  {
    id: 'uuid-23',
    path: 'glow.jpg',
    associatedProject: 'Novel Methods of Tuning Neuroplasticity',
    fundingAmount: 45,
    funder: 'cornperson.eth',
  },
  {
    id: 'uuid-24',
    path: 'helix.jpg',
    associatedProject: 'Novel Methods of Tuning Neuroplasticity',
    fundingAmount: 45,
    funder: 'cornperson.eth',
  },
  {
    id: 'uuid-25',
    path: 'ignition.jpg',
    associatedProject: 'Novel Methods of Tuning Neuroplasticity',
    fundingAmount: 45,
    funder: 'cornperson.eth',
  },
  {
    id: 'uuid-26',
    path: 'iso.jpg',
    associatedProject: 'Novel Methods of Tuning Neuroplasticity',
    fundingAmount: 45,
    funder: 'cornperson.eth',
  },
  {
    id: 'uuid-27',
    path: 'lasers.jpg',
    associatedProject: 'Novel Methods of Tuning Neuroplasticity',
    fundingAmount: 45,
    funder: 'cornperson.eth',
  },
  {
    id: 'uuid-28',
    path: 'molecule.jpg',
    associatedProject: 'Novel Methods of Tuning Neuroplasticity',
    fundingAmount: 45,
    funder: 'cornperson.eth',
  },
  {
    id: 'uuid-29',
    path: 'network.jpg',
    associatedProject: 'Novel Methods of Tuning Neuroplasticity',
    fundingAmount: 45,
    funder: 'cornperson.eth',
  },
  {
    id: 'uuid-30',
    path: 'node.jpg',
    associatedProject: 'Novel Methods of Tuning Neuroplasticity',
    fundingAmount: 45,
    funder: 'cornperson.eth',
  },
  {
    id: 'uuid-31',
    path: 'nucleus.jpg',
    associatedProject: 'Novel Methods of Tuning Neuroplasticity',
    fundingAmount: 45,
    funder: 'cornperson.eth',
  },
  {
    id: 'uuid-32',
    path: 'planets.jpg',
    associatedProject: 'Novel Methods of Tuning Neuroplasticity',
    fundingAmount: 45,
    funder: 'cornperson.eth',
  },
  {
    id: 'uuid-33',
    path: 'portal.jpg',
    associatedProject: 'Novel Methods of Tuning Neuroplasticity',
    fundingAmount: 45,
    funder: 'cornperson.eth',
  },
  {
    id: 'uuid-34',
    path: 'surface.jpg',
    associatedProject: 'Novel Methods of Tuning Neuroplasticity',
    fundingAmount: 45,
    funder: 'cornperson.eth',
  },
  {
    id: 'uuid-35',
    path: 'threads.jpg',
    associatedProject: 'Novel Methods of Tuning Neuroplasticity',
    fundingAmount: 45,
    funder: 'cornperson.eth',
  },
  {
    id: 'uuid-36',
    path: 'tron.jpg',
    associatedProject: 'Novel Methods of Tuning Neuroplasticity',
    fundingAmount: 45,
    funder: 'cornperson.eth',
  },
  {
    id: 'uuid-37',
    path: 'aperture.jpg',
    associatedProject: 'Novel Methods of Tuning Neuroplasticity',
    fundingAmount: 45,
    funder: 'cornperson.eth',
  },
  {
    id: 'uuid-38',
    path: 'cell.jpg',
    associatedProject: 'Novel Methods of Tuning Neuroplasticity',
    fundingAmount: 45,
    funder: 'cornperson.eth',
  },
  {
    id: 'uuid-39',
    path: 'cyber.jpg',
    associatedProject: 'Novel Methods of Tuning Neuroplasticity',
    fundingAmount: 45,
    funder: 'cornperson.eth',
  },
  {
    id: 'uuid-40',
    path: 'flower.jpg',
    associatedProject: 'Novel Methods of Tuning Neuroplasticity',
    fundingAmount: 45,
    funder: 'cornperson.eth',
  },
  {
    id: 'uuid-41',
    path: 'glow.jpg',
    associatedProject: 'Novel Methods of Tuning Neuroplasticity',
    fundingAmount: 45,
    funder: 'cornperson.eth',
  },
  {
    id: 'uuid-42',
    path: 'helix.jpg',
    associatedProject: 'Novel Methods of Tuning Neuroplasticity',
    fundingAmount: 45,
    funder: 'cornperson.eth',
  },
  {
    id: 'uuid-43',
    path: 'ignition.jpg',
    associatedProject: 'Novel Methods of Tuning Neuroplasticity',
    fundingAmount: 45,
    funder: 'cornperson.eth',
  },
  {
    id: 'uuid-44',
    path: 'iso.jpg',
    associatedProject: 'Novel Methods of Tuning Neuroplasticity',
    fundingAmount: 45,
    funder: 'cornperson.eth',
  },
  {
    id: 'uuid-45',
    path: 'lasers.jpg',
    associatedProject: 'Novel Methods of Tuning Neuroplasticity',
    fundingAmount: 45,
    funder: 'cornperson.eth',
  },
  {
    id: 'uuid-46',
    path: 'molecule.jpg',
    associatedProject: 'Novel Methods of Tuning Neuroplasticity',
    fundingAmount: 45,
    funder: 'cornperson.eth',
  },
  {
    id: 'uuid-47',
    path: 'network.jpg',
    associatedProject: 'Novel Methods of Tuning Neuroplasticity',
    fundingAmount: 45,
    funder: 'cornperson.eth',
  },
  {
    id: 'uuid-48',
    path: 'node.jpg',
    associatedProject: 'Novel Methods of Tuning Neuroplasticity',
    fundingAmount: 45,
    funder: 'cornperson.eth',
  },
  {
    id: 'uuid-49',
    path: 'nucleus.jpg',
    associatedProject: 'Novel Methods of Tuning Neuroplasticity',
    fundingAmount: 45,
    funder: 'cornperson.eth',
  },
  {
    id: 'uuid-50',
    path: 'planets.jpg',
    associatedProject: 'Novel Methods of Tuning Neuroplasticity',
    fundingAmount: 45,
    funder: 'cornperson.eth',
  },
  {
    id: 'uuid-51',
    path: 'portal.jpg',
    associatedProject: 'Novel Methods of Tuning Neuroplasticity',
    fundingAmount: 45,
    funder: 'cornperson.eth',
  },
  {
    id: 'uuid-52',
    path: 'surface.jpg',
    associatedProject: 'Novel Methods of Tuning Neuroplasticity',
    fundingAmount: 45,
    funder: 'cornperson.eth',
  },
  {
    id: 'uuid-53',
    path: 'threads.jpg',
    associatedProject: 'Novel Methods of Tuning Neuroplasticity',
    fundingAmount: 45,
    funder: 'cornperson.eth',
  },
  {
    id: 'uuid-54',
    path: 'tron.jpg',
    associatedProject: 'Novel Methods of Tuning Neuroplasticity',
    fundingAmount: 45,
    funder: 'cornperson.eth',
  },
];

export default DUMMY_ARTWORK;
