import Head from 'next/head';
import Image from 'next/image';
import { ReactNode, useState } from 'react';
import { useRouter } from 'next/router';

import hexes from '@/public/site/hexagon-background.png';
import Navbar from './navbar';
import Footer from './footer';

interface LayoutProps {
  children: ReactNode;
}

function Layout({ children }: LayoutProps) {
  const [searchQuery, setSearchQuery] = useState('');
  const router = useRouter();
  const currentPage = router.pathname;

  return (
    <>
      <Head>
        <title>inTheory App</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link
          rel="icon"
          href="/company/intheory.ico"
        />
      </Head>
      <Navbar current={currentPage} />
      <main>
        <div className="bg-container">
          <Image
            className="bg-image"
            src={hexes}
            alt="hexagon background"
            placeholder="blur"
            fill
            sizes="100vw"
          />
        </div>
        {children}
      </main>
      <Footer />
    </>
  );
}

export default Layout;
